language: node_js
node_js:  
  - node

matrix:
  fast_finish: true
  include:
    - os: linux
      name: tests
      tag: true
    - os: osx
      name: tests
      tag: true
    # Build debs
    #- os: osx
    #  name: cydia32
    #  tag: true
    - os: linux
      name: debian-buster
      dist: buster
      tag: true
    - os: linux
      name: ubuntu-1804
      dist: bionic
      tag: true

script:
  - |
    export R2_VERSION="4.5.0"
    upload() {
      if [ "$TRAVIS_BRANCH" == "master" ]; then
        wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh $1*.deb
      else
        echo "Not pushing the deb to release since is not master (actual $TRAVIS_BRANCH)"
      fi
    }
    case "$TRAVIS_JOB_NAME" in
    tests)
      chmod +x travis-test.sh
      ./travis-test.sh
      ;;
    cydia32)
      VERSION="$R2_VERSION" DISTRIB="$TRAVIS_JOB_NAME" CPU="armv7" make -C p/dist/cydia || exit 1
      upload p/dist/cydia/
      ;;
    cydia64)
      VERSION="$R2_VERSION" DISTRIB="$TRAVIS_JOB_NAME" make -C p/dist/cydia || exit 1
      upload p/dist/cydia/
      ;;
    *)
      VERSION="$R2_VERSION" DISTRIB="$TRAVIS_JOB_NAME" make -C p/dist/debian || exit 1
      upload p/dist/debian/
      ;;
    esac

git:
  quiet: true
  depth: 3
