language: node_js

node_js:  
  - 9
  - 8
  - node

os:
  - linux
  - osx

script:
  - npm install eslint
  - export PATH="$PATH:./node_modules/.bin/"
  - chmod +x eslint-check.sh
  - ./eslint-check.sh || echo ""
  - chmod +x travis-test.sh
  - ./travis-test.sh

git:
  depth: 3
