language: node_js
node_js:  
  - node

matrix:
  fast_finish: true
  include:
    - os: linux
      name: Test
    - os: osx
      name: Test
    - os: linux
      name: Debian
      dist: stable

script:
  - |
    case "$TRAVIS_JOB_NAME" in
    Test)
      chmod +x travis-test.sh
      ./travis-test.sh
      ;;
    Debian)
      VERSION="4.4.0" make -C p/dist/debian || exit 0
      wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
      if [ "$TRAVIS_BRANCH" == "master" ]; then
          bash upload.sh p/dist/debian/*.deb
      else
          echo "Not pushing the deb to release since is not master (actual $TRAVIS_BRANCH)"
      fi
      ;;
    esac

git:
  quiet: true
  depth: 3
