language: node_js
node_js:  
  - node

matrix:
  fast_finish: true
  include:
    - os: linux
      name: tests
      tag: true
    - os: osx
      name: tests
      tag: true
    - os: linux
      name: debian-buster
      dist: buster
      tag: true
    - os: linux
      name: ubuntu-1804
      dist: bionic
      tag: true

script:
  - |
    case "$TRAVIS_JOB_NAME" in
    tests)
      chmod +x travis-test.sh
      ./travis-test.sh
      ;;
    debian-buster)
      VERSION="4.5.0" DISTRIB="$TRAVIS_JOB_NAME" make -C p/dist/debian
      wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
      if [ "$TRAVIS_BRANCH" == "master" ]; then
          bash upload.sh p/dist/debian/*.deb
      else
          echo "Not pushing the deb to release since is not master (actual $TRAVIS_BRANCH)"
      fi
      ;;
    ubuntu-1804)
      VERSION="4.5.0" DISTRIB="$TRAVIS_JOB_NAME" make -C p/dist/debian
      wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
      if [ "$TRAVIS_BRANCH" == "master" ]; then
          bash upload.sh p/dist/debian/*.deb
      else
          echo "Not pushing the deb to release since is not master (actual $TRAVIS_BRANCH)"
      fi
      ;;
    esac

git:
  quiet: true
  depth: 3
