language: node_js
node_js:  
  - node

matrix:
  fast_finish: true
  include:
    - os: linux
      name: Test
    - os: osx
      name: Test
    - os: linux
      name: Debian
      dist: trusty

script:
  - |
    case "$TRAVIS_JOB_NAME" in
    Test)
      chmod +x travis-test.sh
      ./travis-test.sh
      ;;
    Debian)
      export VERSION="4.3.1"
      make -C p/dist/debian
      wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
      bash upload.sh p/dist/debian/*.deb
      ;;
    esac

git:
  quiet: true
  depth: 3
